services:
  - type: web
    name: AskMyDoc_v3
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile-frontend
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        value: https://askmydoc-backend-v3.onrender.com
    #   - fromGroup: SmartIntern_env_var  # ✅ Reference your environment group

  - type: web
    name: askmydoc_backend_v3
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile_backend
    autoDeploy: true
    envVars:
      - fromGroup: AskMyDoc_env_var  # ✅ Reference your environment group
